// frontend/src/components/AddWishModal.vue
<script setup lang="ts">
/**
 * Add Wish Modal.
 * Bottom sheet modal to add a new wish.
 */
import { ref, reactive } from 'vue'

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'submit', data: { title: string; price?: number; currency?: string; link?: string; description?: string }): void
}>()

const isSubmitting = ref(false)
const form = reactive({
  title: '',
  price: '',
  currency: 'RUB',
  link: '',
  description: ''
})

function handleSubmit() {
  if (!form.title.trim()) return
  
  isSubmitting.value = true
  
  // Convert price string to number if present
  const priceNumber = form.price ? parseFloat(form.price) : undefined
  
  emit('submit', {
    title: form.title,
    price: priceNumber,
    currency: form.currency,
    link: form.link,
    description: form.description
  })
}

function onInputFocus(event: FocusEvent) {
  setTimeout(() => {
    (event.target as HTMLElement).scrollIntoView({ behavior: 'smooth', block: 'center' })
  }, 300)
}
</script>

<template>
  <div class="modal-overlay" @click.self="$emit('close')">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Новое желание</h3>
        <button class="close-btn" @click="$emit('close')">✕</button>
      </div>

      <form @submit.prevent="handleSubmit" class="wish-form">
        <div class="form-group">
          <label>Название*</label>
          <input
            v-model="form.title"
            type="text"
            placeholder="Что вы хотите?"
            required
            autofocus
            @focus="onInputFocus"
          />
        </div>

        <div class="form-row">
          <div class="form-group">
            <label>Цена</label>
            <input
              v-model="form.price"
              type="number"
              placeholder="0"
              min="0"
              @focus="onInputFocus"
            />
          </div>
          <div class="form-group currency-group">
            <label>Валюта</label>
            <select v-model="form.currency" @focus="onInputFocus">
              <option value="RUB">RUB</option>
              <option value="USD">USD</option>
              <option value="EUR">EUR</option>
            </select>
          </div>
        </div>

        <div class="form-group">
          <label>Ссылка</label>
          <input
            v-model="form.link"
            type="url"
            placeholder="https://..."
            @focus="onInputFocus"
          />
        </div>

        <div class="form-group">
          <label>Описание</label>
          <textarea
            v-model="form.description"
            rows="3"
            placeholder="Размер, цвет, детали..."
            @focus="onInputFocus"
          ></textarea>
        </div>

        <button
          type="submit"
          class="submit-btn"
          :disabled="isSubmitting || !form.title.trim()"
        >
          {{ isSubmitting ? 'Добавление...' : 'Добавить желание' }}
        </button>
      </form>
    </div>
  </div>
</template>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: flex-end; /* Bottom sheet */
  z-index: 1000;
  animation: fade-in 0.2s ease-out;
}

.modal-content {
  width: 100%;
  background: white;
  border-radius: 24px 24px 0 0;
  padding: 24px;
  max-height: 90vh;
  overflow-y: auto;
  animation: slide-up 0.3s cubic-bezier(0.2, 0.8, 0.2, 1);
  padding-bottom: max(24px, env(safe-area-inset-bottom));
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
}

.modal-header h3 {
  margin: 0;
  font-size: 20px;
  font-weight: 700;
}

.close-btn {
  background: none;
  border: none;
  font-size: 20px;
  color: var(--tg-hint-color, #999);
  padding: 8px;
  cursor: pointer;
}

.wish-form {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.form-row {
  display: flex;
  gap: 12px;
}

.form-row .form-group {
  flex: 1;
}

.currency-group {
  flex: 0 0 80px;
}

label {
  font-size: 13px;
  font-weight: 500;
  color: var(--tg-hint-color, #777);
  margin-left: 4px;
}

input, select, textarea {
  width: 100%;
  padding: 12px 16px;
  border: 1px solid #eee;
  border-radius: 12px;
  font-size: 16px;
  background: #f9f9f9;
  transition: all 0.2s;
  font-family: inherit;
  box-sizing: border-box; /* Crucial for inputs */
}

input:focus, select:focus, textarea:focus {
  outline: none;
  border-color: var(--tg-button-color, #3390ec);
  background: white;
}

.submit-btn {
  margin-top: 16px;
  padding: 16px;
  background: var(--tg-button-color, #3390ec);
  color: white;
  border: none;
  border-radius: 14px;
  font-size: 16px;
  font-weight: 700;
  cursor: pointer;
  transition: opacity 0.2s;
}

.submit-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

@keyframes fade-in {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes slide-up {
  from { transform: translateY(100%); }
  to { transform: translateY(0); }
}
</style>

// components/AddWishModal.tsx
import React, { useState, useEffect } from 'react';
import { Wish, PriorityLevel } from '../types';
import { X, Star, Link as LinkIcon, DollarSign, Type } from 'lucide-react';

interface AddWishModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (wish: Partial<Wish>) => void;
  initialWish?: Wish | null;
}

const AddWishModal: React.FC<AddWishModalProps> = ({ isOpen, onClose, onSave, initialWish }) => {
  const [title, setTitle] = useState('');
  const [price, setPrice] = useState('');
  const [url, setUrl] = useState('');
  const [comment, setComment] = useState('');
  const [priority, setPriority] = useState<PriorityLevel>(3);

  useEffect(() => {
    if (initialWish) {
      setTitle(initialWish.title);
      setPrice(initialWish.price?.toString() || '');
      setUrl(initialWish.url || '');
      setComment(initialWish.comment || '');
      setPriority(initialWish.priority);
    } else {
      resetForm();
    }
  }, [initialWish, isOpen]);

  const resetForm = () => {
    setTitle('');
    setPrice('');
    setUrl('');
    setComment('');
    setPriority(3);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    let finalUrl = url;
    if (url && !url.startsWith('http')) {
      finalUrl = `https://${url}`;
    }

    // We pass a partial wish object. ID and EventID are handled by parent/backend
    const newWish: any = {
      title,
      price: price ? parseFloat(price) : undefined,
      currency: '₽',
      url: finalUrl,
      priority,
      comment,
      image_url: initialWish?.image_url,
    };

    onSave(newWish);
    resetForm();
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/50 backdrop-blur-sm transition-opacity">
      <div className="bg-white w-full max-w-md rounded-t-2xl sm:rounded-2xl p-6 shadow-2xl animate-slide-up sm:animate-fade-in max-h-[90vh] overflow-y-auto">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-bold text-gray-800">
            {initialWish ? 'Редактировать' : 'Новое желание'}
          </h2>
          <button onClick={onClose} className="p-2 bg-gray-100 rounded-full text-gray-500">
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-1">
            <label className="text-sm font-medium text-gray-700 ml-1">Название</label>
            <div className="relative">
              <Type className="absolute left-3 top-3 text-gray-400" size={18} />
              <input
                required
                type="text"
                placeholder="например, Яндекс Станция"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none transition-all"
              />
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-sm font-medium text-gray-700 ml-1">Ссылка (необязательно)</label>
            <div className="relative">
              <LinkIcon className="absolute left-3 top-3 text-gray-400" size={18} />
              <input
                type="text"
                placeholder="https://..."
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                className="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none transition-all"
              />
            </div>
          </div>

          <div className="flex gap-4">
            <div className="flex-1 space-y-1">
              <label className="text-sm font-medium text-gray-700 ml-1">Цена (₽)</label>
              <div className="relative">
                <DollarSign className="absolute left-3 top-3 text-gray-400" size={18} />
                <input
                  type="number"
                  placeholder="0"
                  value={price}
                  onChange={(e) => setPrice(e.target.value)}
                  className="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none transition-all"
                />
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-700 ml-1">Как сильно хочется?</label>
            <div className="flex justify-between bg-gray-50 p-3 rounded-xl border border-gray-200">
              {[1, 2, 3, 4, 5].map((star) => (
                <button
                  key={star}
                  type="button"
                  onClick={() => setPriority(star as PriorityLevel)}
                  className="focus:outline-none transform transition-transform active:scale-110"
                >
                  <Star
                    size={28}
                    className={`${star <= priority ? 'fill-yellow-400 text-yellow-400' : 'text-gray-300'
                      }`}
                  />
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-sm font-medium text-gray-700 ml-1">Комментарий / Описание</label>
            <textarea
              rows={3}
              placeholder="Цвет, размер, или почему это так важно..."
              value={comment}
              onChange={(e) => setComment(e.target.value)}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:outline-none transition-all resize-none"
            />
          </div>

          <button
            type="submit"
            className="w-full py-4 bg-blue-600 text-white font-bold rounded-xl shadow-lg shadow-blue-200 active:scale-95 transition-all mt-4"
          >
            {initialWish ? 'Сохранить' : 'Добавить'}
          </button>
        </form>
      </div>
    </div>
  );
};

export default AddWishModal;
